# Service will be executed by order (A-Z).
version: '3.8'
services:
  pg:
    image: postgres:latest
    ports:
     - "4321:5432" # exposed-port:container-port
    environment:
     - POSTGRES_USER=dev
     - POSTGRES_PASSWORD=databasemahal
     - POSTGRES_DB=db_exercise
    volumes:
     - ./docker_pg_init.sql:/docker-entrypoint-initdb.d/docker_pg_init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d db_exercise"]
      interval: 5s
      timeout: 2s
      retries: 3
  server:
    build : .
    ports:
      - 8080:8080 # exposed-port:container-port
    depends_on:
      pg:
        condition: service_healthy
    environment:
      - DB_USER=dev
      - DB_PASSWORD=databasemahal
      - DB_HOST=pg
      - DB_PORT=5432
      - DB_DATABASE=db_exercise
      - SERVER_PORT=8080
