version: '3.8'
services:
  db:
    image: postgres:latest
    ports:
     - "4321:5432" #exposed-port:container-port
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=databasemahal
     - POSTGRES_DB=db_exercise
    volumes:
     - ./docker_pg_init.sql:/docker-entrypoint-initdb.d/docker_pg_init.sql
  backend:
    build : .
    ports:
      - 8080:8080 #exposed-port:container-port
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=databasemahal
      - DB_DATABASE=db_exercise
      - DB_PORT=5432
      - SERVER_PORT=8080
    depends_on:
      - db
